[package]
name = "vr360-coding-assessment"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.0", features = ["postgres"] }
serde = { version = "1.0.210", features = ["derive"] }
